export type CurrencyDefinition = {
  code: string;
  name: string;
  countries: string[];
  symbol: string;
};

export const DEFAULT_CURRENCY_CODE = "MYR";

export const CURRENCIES: CurrencyDefinition[] = [
  {
    code: "AED",
    name: "UAE Dirham",
    symbol: "د.إ",
    countries: ["United Arab Emirates"],
  },
  {
    code: "AFN",
    name: "Afghan Afghani",
    symbol: "؋",
    countries: ["Afghanistan"],
  },
  { code: "ALL", name: "Albanian Lek", symbol: "L", countries: ["Albania"] },
  { code: "AMD", name: "Armenian Dram", symbol: "֏", countries: ["Armenia"] },
  { code: "AOA", name: "Angolan Kwanza", symbol: "Kz", countries: ["Angola"] },
  {
    code: "ARS",
    name: "Argentine Peso",
    symbol: "$",
    countries: ["Argentina"],
  },
  {
    code: "AUD",
    name: "Australian Dollar",
    symbol: "A$",
    countries: [
      "Australia",
      "Christmas Island",
      "Cocos (Keeling) Islands",
      "Heard Island and McDonald Islands",
      "Kiribati",
      "Nauru",
      "Norfolk Island",
      "Tuvalu",
    ],
  },
  { code: "AWG", name: "Aruban Florin", symbol: "ƒ", countries: ["Aruba"] },
  {
    code: "AZN",
    name: "Azerbaijani Manat",
    symbol: "₼",
    countries: ["Azerbaijan"],
  },
  {
    code: "BAM",
    name: "Bosnia-Herzegovina Convertible Mark",
    symbol: "KM",
    countries: ["Bosnia and Herzegovina"],
  },
  {
    code: "BBD",
    name: "Barbadian Dollar",
    symbol: "Bds$",
    countries: ["Barbados"],
  },
  {
    code: "BDT",
    name: "Bangladeshi Taka",
    symbol: "৳",
    countries: ["Bangladesh"],
  },
  {
    code: "BHD",
    name: "Bahraini Dinar",
    symbol: "د.ب",
    countries: ["Bahrain"],
  },
  {
    code: "BIF",
    name: "Burundian Franc",
    symbol: "FBu",
    countries: ["Burundi"],
  },
  {
    code: "BMD",
    name: "Bermudian Dollar",
    symbol: "BD$",
    countries: ["Bermuda"],
  },
  { code: "BND", name: "Brunei Dollar", symbol: "B$", countries: ["Brunei"] },
  {
    code: "BOB",
    name: "Bolivian Boliviano",
    symbol: "Bs.",
    countries: ["Bolivia"],
  },
  { code: "BRL", name: "Brazilian Real", symbol: "R$", countries: ["Brazil"] },
  {
    code: "BSD",
    name: "Bahamian Dollar",
    symbol: "B$",
    countries: ["Bahamas"],
  },
  {
    code: "BTN",
    name: "Bhutanese Ngultrum",
    symbol: "Nu.",
    countries: ["Bhutan"],
  },
  { code: "BWP", name: "Botswana Pula", symbol: "P", countries: ["Botswana"] },
  {
    code: "BYN",
    name: "Belarusian Ruble",
    symbol: "Br",
    countries: ["Belarus"],
  },
  { code: "BZD", name: "Belize Dollar", symbol: "BZ$", countries: ["Belize"] },
  { code: "CAD", name: "Canadian Dollar", symbol: "C$", countries: ["Canada"] },
  {
    code: "CDF",
    name: "Congolese Franc",
    symbol: "FC",
    countries: ["Democratic Republic of the Congo", "Congo-Kinshasa"],
  },
  {
    code: "CHF",
    name: "Swiss Franc",
    symbol: "CHF",
    countries: ["Switzerland", "Liechtenstein"],
  },
  { code: "CLP", name: "Chilean Peso", symbol: "$", countries: ["Chile"] },
  {
    code: "CNY",
    name: "Chinese Yuan Renminbi",
    symbol: "¥",
    countries: ["China"],
  },
  { code: "COP", name: "Colombian Peso", symbol: "$", countries: ["Colombia"] },
  {
    code: "CRC",
    name: "Costa Rican Colón",
    symbol: "₡",
    countries: ["Costa Rica"],
  },
  { code: "CUP", name: "Cuban Peso", symbol: "$", countries: ["Cuba"] },
  {
    code: "CVE",
    name: "Cape Verdean Escudo",
    symbol: "Esc",
    countries: ["Cabo Verde", "Cape Verde"],
  },
  {
    code: "CZK",
    name: "Czech Koruna",
    symbol: "Kč",
    countries: ["Czechia", "Czech Republic"],
  },
  {
    code: "DJF",
    name: "Djiboutian Franc",
    symbol: "Fdj",
    countries: ["Djibouti"],
  },
  {
    code: "DKK",
    name: "Danish Krone",
    symbol: "kr",
    countries: ["Denmark", "Faroe Islands", "Greenland"],
  },
  {
    code: "DOP",
    name: "Dominican Peso",
    symbol: "RD$",
    countries: ["Dominican Republic"],
  },
  { code: "DZD", name: "Algerian Dinar", symbol: "دج", countries: ["Algeria"] },
  { code: "EGP", name: "Egyptian Pound", symbol: "E£", countries: ["Egypt"] },
  {
    code: "ERN",
    name: "Eritrean Nakfa",
    symbol: "Nfk",
    countries: ["Eritrea"],
  },
  {
    code: "ETB",
    name: "Ethiopian Birr",
    symbol: "Br",
    countries: ["Ethiopia"],
  },
  {
    code: "EUR",
    name: "Euro",
    symbol: "€",
    countries: [
      "Andorra",
      "Austria",
      "Belgium",
      "Bulgaria",
      "Croatia",
      "Cyprus",
      "Estonia",
      "Finland",
      "France",
      "French Guiana",
      "French Southern Territories",
      "Germany",
      "Greece",
      "Guadeloupe",
      "Ireland",
      "Italy",
      "Kosovo",
      "Latvia",
      "Lithuania",
      "Luxembourg",
      "Malta",
      "Martinique",
      "Mayotte",
      "Monaco",
      "Montenegro",
      "Netherlands",
      "Portugal",
      "Réunion",
      "Saint Barthélemy",
      "Saint Martin",
      "Saint Pierre and Miquelon",
      "San Marino",
      "Slovakia",
      "Slovenia",
      "Spain",
      "Vatican City",
      "Åland Islands",
    ],
  },
  { code: "FJD", name: "Fijian Dollar", symbol: "FJ$", countries: ["Fiji"] },
  {
    code: "FKP",
    name: "Falkland Islands Pound",
    symbol: "£",
    countries: ["Falkland Islands"],
  },
  {
    code: "GBP",
    name: "Pound Sterling",
    symbol: "£",
    countries: [
      "United Kingdom",
      "England",
      "Scotland",
      "Wales",
      "Northern Ireland",
      "Guernsey",
      "Isle of Man",
      "Jersey",
      "South Georgia and the South Sandwich Islands",
    ],
  },
  { code: "GEL", name: "Georgian Lari", symbol: "₾", countries: ["Georgia"] },
  { code: "GHS", name: "Ghanaian Cedi", symbol: "₵", countries: ["Ghana"] },
  {
    code: "GIP",
    name: "Gibraltar Pound",
    symbol: "£",
    countries: ["Gibraltar"],
  },
  { code: "GMD", name: "Gambian Dalasi", symbol: "D", countries: ["Gambia"] },
  { code: "GNF", name: "Guinean Franc", symbol: "FG", countries: ["Guinea"] },
  {
    code: "GTQ",
    name: "Guatemalan Quetzal",
    symbol: "Q",
    countries: ["Guatemala"],
  },
  { code: "GYD", name: "Guyanese Dollar", symbol: "G$", countries: ["Guyana"] },
  {
    code: "HKD",
    name: "Hong Kong Dollar",
    symbol: "HK$",
    countries: ["Hong Kong"],
  },
  {
    code: "HNL",
    name: "Honduran Lempira",
    symbol: "L",
    countries: ["Honduras"],
  },
  { code: "HTG", name: "Haitian Gourde", symbol: "G", countries: ["Haiti"] },
  {
    code: "HUF",
    name: "Hungarian Forint",
    symbol: "Ft",
    countries: ["Hungary"],
  },
  {
    code: "IDR",
    name: "Indonesian Rupiah",
    symbol: "Rp",
    countries: ["Indonesia"],
  },
  {
    code: "ILS",
    name: "Israeli New Shekel",
    symbol: "₪",
    countries: ["Israel", "Palestine", "Palestinian Territories"],
  },
  {
    code: "INR",
    name: "Indian Rupee",
    symbol: "₹",
    countries: ["India", "Bhutan"],
  },
  { code: "IQD", name: "Iraqi Dinar", symbol: "ع.د", countries: ["Iraq"] },
  { code: "IRR", name: "Iranian Rial", symbol: "﷼", countries: ["Iran"] },
  {
    code: "ISK",
    name: "Icelandic Króna",
    symbol: "kr",
    countries: ["Iceland"],
  },
  {
    code: "JMD",
    name: "Jamaican Dollar",
    symbol: "J$",
    countries: ["Jamaica"],
  },
  {
    code: "JOD",
    name: "Jordanian Dinar",
    symbol: "د.ا",
    countries: ["Jordan"],
  },
  { code: "JPY", name: "Japanese Yen", symbol: "¥", countries: ["Japan"] },
  { code: "KES", name: "Kenyan Shilling", symbol: "KSh", countries: ["Kenya"] },
  {
    code: "KGS",
    name: "Kyrgyzstani Som",
    symbol: "сом",
    countries: ["Kyrgyzstan"],
  },
  { code: "KHR", name: "Cambodian Riel", symbol: "៛", countries: ["Cambodia"] },
  { code: "KMF", name: "Comorian Franc", symbol: "CF", countries: ["Comoros"] },
  {
    code: "KPW",
    name: "North Korean Won",
    symbol: "₩",
    countries: ["North Korea"],
  },
  {
    code: "KRW",
    name: "South Korean Won",
    symbol: "₩",
    countries: ["South Korea"],
  },
  { code: "KWD", name: "Kuwaiti Dinar", symbol: "د.ك", countries: ["Kuwait"] },
  {
    code: "KYD",
    name: "Cayman Islands Dollar",
    symbol: "CI$",
    countries: ["Cayman Islands"],
  },
  {
    code: "KZT",
    name: "Kazakhstani Tenge",
    symbol: "₸",
    countries: ["Kazakhstan"],
  },
  {
    code: "LAK",
    name: "Lao Kip",
    symbol: "₭",
    countries: ["Laos", "Lao People's Democratic Republic"],
  },
  {
    code: "LBP",
    name: "Lebanese Pound",
    symbol: "ل.ل",
    countries: ["Lebanon"],
  },
  {
    code: "LKR",
    name: "Sri Lankan Rupee",
    symbol: "Rs",
    countries: ["Sri Lanka"],
  },
  {
    code: "LRD",
    name: "Liberian Dollar",
    symbol: "L$",
    countries: ["Liberia"],
  },
  { code: "LSL", name: "Lesotho Loti", symbol: "L", countries: ["Lesotho"] },
  { code: "LYD", name: "Libyan Dinar", symbol: "ل.د", countries: ["Libya"] },
  {
    code: "MAD",
    name: "Moroccan Dirham",
    symbol: "د.م.",
    countries: ["Morocco", "Western Sahara"],
  },
  { code: "MDL", name: "Moldovan Leu", symbol: "L", countries: ["Moldova"] },
  {
    code: "MGA",
    name: "Malagasy Ariary",
    symbol: "Ar",
    countries: ["Madagascar"],
  },
  {
    code: "MKD",
    name: "Macedonian Denar",
    symbol: "ден",
    countries: ["North Macedonia"],
  },
  {
    code: "MMK",
    name: "Myanmar Kyat",
    symbol: "K",
    countries: ["Myanmar", "Burma"],
  },
  {
    code: "MNT",
    name: "Mongolian Tögrög",
    symbol: "₮",
    countries: ["Mongolia"],
  },
  {
    code: "MOP",
    name: "Macanese Pataca",
    symbol: "MOP$",
    countries: ["Macao", "Macau"],
  },
  {
    code: "MRU",
    name: "Mauritanian Ouguiya",
    symbol: "UM",
    countries: ["Mauritania"],
  },
  {
    code: "MUR",
    name: "Mauritian Rupee",
    symbol: "₨",
    countries: ["Mauritius"],
  },
  {
    code: "MVR",
    name: "Maldivian Rufiyaa",
    symbol: "Rf",
    countries: ["Maldives"],
  },
  { code: "MWK", name: "Malawian Kwacha", symbol: "MK", countries: ["Malawi"] },
  { code: "MXN", name: "Mexican Peso", symbol: "MX$", countries: ["Mexico"] },
  {
    code: "MYR",
    name: "Malaysian Ringgit",
    symbol: "RM",
    countries: ["Malaysia"],
  },
  {
    code: "MZN",
    name: "Mozambican Metical",
    symbol: "MT",
    countries: ["Mozambique"],
  },
  {
    code: "NAD",
    name: "Namibian Dollar",
    symbol: "N$",
    countries: ["Namibia"],
  },
  { code: "NGN", name: "Nigerian Naira", symbol: "₦", countries: ["Nigeria"] },
  {
    code: "NIO",
    name: "Nicaraguan Córdoba",
    symbol: "C$",
    countries: ["Nicaragua"],
  },
  {
    code: "NOK",
    name: "Norwegian Krone",
    symbol: "kr",
    countries: ["Norway", "Bouvet Island", "Svalbard and Jan Mayen"],
  },
  { code: "NPR", name: "Nepalese Rupee", symbol: "रू", countries: ["Nepal"] },
  {
    code: "NZD",
    name: "New Zealand Dollar",
    symbol: "NZ$",
    countries: [
      "New Zealand",
      "Cook Islands",
      "Niue",
      "Pitcairn Islands",
      "Tokelau",
    ],
  },
  { code: "OMR", name: "Omani Rial", symbol: "ر.ع.", countries: ["Oman"] },
  {
    code: "PAB",
    name: "Panamanian Balboa",
    symbol: "B/.",
    countries: ["Panama"],
  },
  { code: "PEN", name: "Peruvian Sol", symbol: "S/", countries: ["Peru"] },
  {
    code: "PGK",
    name: "Papua New Guinean Kina",
    symbol: "K",
    countries: ["Papua New Guinea"],
  },
  {
    code: "PHP",
    name: "Philippine Peso",
    symbol: "₱",
    countries: ["Philippines"],
  },
  {
    code: "PKR",
    name: "Pakistani Rupee",
    symbol: "₨",
    countries: ["Pakistan"],
  },
  { code: "PLN", name: "Polish Złoty", symbol: "zł", countries: ["Poland"] },
  {
    code: "PYG",
    name: "Paraguayan Guaraní",
    symbol: "₲",
    countries: ["Paraguay"],
  },
  { code: "QAR", name: "Qatari Riyal", symbol: "ر.ق", countries: ["Qatar"] },
  { code: "RON", name: "Romanian Leu", symbol: "lei", countries: ["Romania"] },
  { code: "RSD", name: "Serbian Dinar", symbol: "дин", countries: ["Serbia"] },
  {
    code: "RUB",
    name: "Russian Ruble",
    symbol: "₽",
    countries: ["Russia", "Russian Federation"],
  },
  { code: "RWF", name: "Rwandan Franc", symbol: "FRw", countries: ["Rwanda"] },
  {
    code: "SAR",
    name: "Saudi Riyal",
    symbol: "ر.س",
    countries: ["Saudi Arabia"],
  },
  {
    code: "SBD",
    name: "Solomon Islands Dollar",
    symbol: "SI$",
    countries: ["Solomon Islands"],
  },
  {
    code: "SCR",
    name: "Seychellois Rupee",
    symbol: "₨",
    countries: ["Seychelles"],
  },
  { code: "SDG", name: "Sudanese Pound", symbol: "ج.س.", countries: ["Sudan"] },
  { code: "SEK", name: "Swedish Krona", symbol: "kr", countries: ["Sweden"] },
  {
    code: "SGD",
    name: "Singapore Dollar",
    symbol: "S$",
    countries: ["Singapore"],
  },
  {
    code: "SHP",
    name: "Saint Helena Pound",
    symbol: "£",
    countries: ["Saint Helena", "Ascension Island", "Tristan da Cunha"],
  },
  {
    code: "SLE",
    name: "Sierra Leonean Leone",
    symbol: "Le",
    countries: ["Sierra Leone"],
  },
  {
    code: "SOS",
    name: "Somali Shilling",
    symbol: "Sh",
    countries: ["Somalia"],
  },
  {
    code: "SRD",
    name: "Surinamese Dollar",
    symbol: "$",
    countries: ["Suriname"],
  },
  {
    code: "SSP",
    name: "South Sudanese Pound",
    symbol: "£",
    countries: ["South Sudan"],
  },
  {
    code: "STN",
    name: "São Tomé and Príncipe Dobra",
    symbol: "Db",
    countries: ["São Tomé and Príncipe"],
  },
  {
    code: "SVC",
    name: "Salvadoran Colón",
    symbol: "₡",
    countries: ["El Salvador"],
  },
  { code: "SYP", name: "Syrian Pound", symbol: "£", countries: ["Syria"] },
  {
    code: "SZL",
    name: "Swazi Lilangeni",
    symbol: "L",
    countries: ["Eswatini", "Swaziland"],
  },
  { code: "THB", name: "Thai Baht", symbol: "฿", countries: ["Thailand"] },
  {
    code: "TJS",
    name: "Tajikistani Somoni",
    symbol: "ЅМ",
    countries: ["Tajikistan"],
  },
  {
    code: "TMT",
    name: "Turkmenistani Manat",
    symbol: "m",
    countries: ["Turkmenistan"],
  },
  {
    code: "TND",
    name: "Tunisian Dinar",
    symbol: "د.ت",
    countries: ["Tunisia"],
  },
  { code: "TOP", name: "Tongan Paʻanga", symbol: "T$", countries: ["Tonga"] },
  {
    code: "TRY",
    name: "Turkish Lira",
    symbol: "₺",
    countries: ["Türkiye", "Turkey"],
  },
  {
    code: "TTD",
    name: "Trinidad and Tobago Dollar",
    symbol: "TT$",
    countries: ["Trinidad and Tobago"],
  },
  {
    code: "TWD",
    name: "New Taiwan Dollar",
    symbol: "NT$",
    countries: ["Taiwan"],
  },
  {
    code: "TZS",
    name: "Tanzanian Shilling",
    symbol: "TSh",
    countries: ["Tanzania"],
  },
  {
    code: "UAH",
    name: "Ukrainian Hryvnia",
    symbol: "₴",
    countries: ["Ukraine"],
  },
  {
    code: "UGX",
    name: "Ugandan Shilling",
    symbol: "USh",
    countries: ["Uganda"],
  },
  {
    code: "USD",
    name: "US Dollar",
    symbol: "$",
    countries: [
      "United States",
      "American Samoa",
      "British Indian Ocean Territory",
      "Ecuador",
      "El Salvador",
      "Guam",
      "Haiti",
      "Marshall Islands",
      "Micronesia",
      "Northern Mariana Islands",
      "Palau",
      "Panama",
      "Puerto Rico",
      "Timor-Leste",
      "Turks and Caicos Islands",
      "United States Minor Outlying Islands",
      "US Virgin Islands",
      "British Virgin Islands",
      "Zimbabwe",
    ],
  },
  { code: "UYU", name: "Uruguayan Peso", symbol: "$U", countries: ["Uruguay"] },
  {
    code: "UZS",
    name: "Uzbekistani Som",
    symbol: "soʻm",
    countries: ["Uzbekistan"],
  },
  {
    code: "VES",
    name: "Venezuelan Bolívar",
    symbol: "Bs.",
    countries: ["Venezuela"],
  },
  { code: "VND", name: "Vietnamese Đồng", symbol: "₫", countries: ["Vietnam"] },
  { code: "VUV", name: "Vanuatu Vatu", symbol: "VT", countries: ["Vanuatu"] },
  { code: "WST", name: "Samoan Tālā", symbol: "WS$", countries: ["Samoa"] },
  {
    code: "XAF",
    name: "Central African CFA Franc",
    symbol: "FCFA",
    countries: [
      "Cameroon",
      "Central African Republic",
      "Chad",
      "Republic of the Congo",
      "Congo-Brazzaville",
      "Equatorial Guinea",
      "Gabon",
    ],
  },
  {
    code: "XCD",
    name: "East Caribbean Dollar",
    symbol: "EC$",
    countries: [
      "Anguilla",
      "Antigua and Barbuda",
      "Dominica",
      "Grenada",
      "Montserrat",
      "Saint Kitts and Nevis",
      "Saint Lucia",
      "Saint Vincent and the Grenadines",
    ],
  },
  {
    code: "XCG",
    name: "Caribbean Guilder",
    symbol: "Cg",
    countries: ["Curaçao", "Sint Maarten"],
  },
  {
    code: "XOF",
    name: "West African CFA Franc",
    symbol: "CFA",
    countries: [
      "Benin",
      "Burkina Faso",
      "Côte d’Ivoire",
      "Guinea-Bissau",
      "Mali",
      "Niger",
      "Senegal",
      "Togo",
    ],
  },
  {
    code: "XPF",
    name: "CFP Franc",
    symbol: "₣",
    countries: ["French Polynesia", "New Caledonia", "Wallis and Futuna"],
  },
  { code: "YER", name: "Yemeni Rial", symbol: "﷼", countries: ["Yemen"] },
  {
    code: "ZAR",
    name: "South African Rand",
    symbol: "R",
    countries: ["South Africa", "Lesotho", "Namibia"],
  },
  { code: "ZMW", name: "Zambian Kwacha", symbol: "ZK", countries: ["Zambia"] },
  {
    code: "ZWG",
    name: "Zimbabwe Gold",
    symbol: "ZiG",
    countries: ["Zimbabwe"],
  },
];

export const CURRENCY_CODES = new Set(CURRENCIES.map(({ code }) => code));

export const DEFAULT_CURRENCY_DECIMAL_DIGITS = 2;
export const MAX_CURRENCY_DECIMAL_DIGITS = 3;

const ZERO_DECIMAL_CURRENCY_CODES = new Set([
  "AFN",
  "ALL",
  "BIF",
  "CLP",
  "COP",
  "DJF",
  "GNF",
  "HUF",
  "IDR",
  "IQD",
  "IRR",
  "ISK",
  "JPY",
  "KMF",
  "KPW",
  "KRW",
  "LAK",
  "LBP",
  "MGA",
  "MMK",
  "PKR",
  "PYG",
  "RWF",
  "SOS",
  "SYP",
  "UGX",
  "VND",
  "VUV",
  "XAF",
  "XOF",
  "XPF",
  "YER",
]);

const THREE_DECIMAL_CURRENCY_CODES = new Set([
  "BHD",
  "JOD",
  "KWD",
  "LYD",
  "OMR",
  "TND",
]);

export const CURRENCY_DECIMAL_DIGITS: Readonly<Record<string, number>> =
  Object.freeze(
    Object.fromEntries(
      CURRENCIES.map(({ code }) => [
        code,
        ZERO_DECIMAL_CURRENCY_CODES.has(code)
          ? 0
          : THREE_DECIMAL_CURRENCY_CODES.has(code)
            ? 3
            : DEFAULT_CURRENCY_DECIMAL_DIGITS,
      ]),
    ),
  );

export const getCurrencyDecimalDigits = (currencyCode?: string): number =>
  currencyCode
    ? (CURRENCY_DECIMAL_DIGITS[currencyCode] ?? DEFAULT_CURRENCY_DECIMAL_DIGITS)
    : DEFAULT_CURRENCY_DECIMAL_DIGITS;
